### ISSUE TITLE
Does groovy DSL rule require special methods to compile?

### ISSUE THREAD

**Issue by qq291462491** [zhaber/grules#4]
When I follow your way to achieve a simple check function, I got this wrong message:
```
Caught: groovy.lang.MissingPropertyException: toPositiveInt
groovy.lang.MissingPropertyException: toPositiveInt
	at org.grules.script.RulesScript.propertyMissing(RulesScript.groovy:295)
	at org.grules.script.RulesScript.propertyMissing(RulesScript.groovy)
	at org.grules.test.Hello.run(Hello.groovy:8)
	at org.grules.script.RulesScript.applyRules(RulesScript.groovy:325)
	at org.grules.script.RuleEngine.runScript(RuleEngine.groovy:103)
	at org.grules.script.RuleEngine.this$2$runScript(RuleEngine.groovy)
	at org.grules.script.RuleEngine$this$2$runScript$0.callCurrent(Unknown Source)
	at org.grules.script.RuleEngine.runMainScript(RuleEngine.groovy:80)
	at org.grules.script.RuleEngine.this$2$runMainScript(RuleEngine.groovy)
	at org.grules.script.RuleEngine$_newExecutor_closure1.doCall(RuleEngine.groovy:38)
	at org.grules.GrulesAPI.applyRules(GrulesAPI.groovy:23)
	at org.grules.GrulesAPI$applyRules.call(Unknown Source)
	at org.grules.Grules.applyRules(Grules.groovy:48)
	at org.grules.Grules.applyRules(Grules.groovy)
	at org.grules.Grules$applyRules.call(Unknown Source)
```

 Hello.groovy
```
package com.meituan.hotel.heimdall.groovy

/**
 * Created by liuxinyu on 16/1/4.
 */

id toPositiveInt ["id invalid"] >> {it > 7} ["id more than 7"]

email isEmail ["email invalid"]

age toPositiveInt ["age invalid"] >> {it > 18} ["You must be an adult"]
```

HelloTest.groovy
```
def result = new Grules().applyRules(Hello, [age: "4"])
println result
```

But there's no problem with the example you gave.Then I contrast the contrast.
I found your file like this    
```
import groovy.lang.Binding;
import groovy.lang.Script;
import org.codehaus.groovy.runtime.BytecodeInterface8;
import org.codehaus.groovy.runtime.GeneratedClosure;
import org.codehaus.groovy.runtime.InvokerHelper;
import org.codehaus.groovy.runtime.ScriptBytecodeAdapter;
import org.codehaus.groovy.runtime.callsite.CallSite;
import org.grules.functions.lib.TypeFunctions;
import org.grules.functions.lib.UserFunctions;
import org.grules.script.expressions.FunctionTerm;
import org.grules.script.expressions.SubrulesSeqWrapper;

public class HelloGrules extends Script {
....
```
But my file like this
```
import groovy.lang.Binding;
import groovy.lang.Script;
import org.codehaus.groovy.runtime.BytecodeInterface8;
import org.codehaus.groovy.runtime.GeneratedClosure;
import org.codehaus.groovy.runtime.InvokerHelper;
import org.codehaus.groovy.runtime.ScriptBytecodeAdapter;
import org.codehaus.groovy.runtime.callsite.CallSite;

public class Hello extends Script {
```

**Comment by qq291462491** [comment]
It seems to be no entry into force for AST Transformation.

**Comment by zhaber** [comment]
The naming convention is that the script file name should end with the suffix Grules. I will add a check to make the root cause more clear. Documentation for the sample rules script was updated to reflect this convention.

**Comment by qq291462491** [comment]
Oh,got it,suggest Indicate it in the wiki.

**Comment by zhaber** [comment]
Commit which checks the script name: https://github.com/zhaber/grules/commit/19f1a386858a42855c86b7c5011db90bf01e74bb
